apiVersion: v1
kind: Service
metadata:
  name: usermgmt-webapp-service
spec:
  type: LoadBalancer #cluserIp #NodePort
  selector: #matchexpression
    app: usermgmt-webapp 
  ports:
    - port: 80 #service Port
      targetPort: 8080 #container port