apiVersion: v1
kind: ConfigMap
metadata:
  name: usermanagement-dbcreation-script
data:
  mysql_usermgmt.sql: |-
    DROP DATABASE IF EXISTS webappdb;
    CREATE DATABASE webappdb;
  #this two value i am injecting inside my mysql pod.
  # when i deploy my database it will autmatically modify the db and create and db inside my pod with the name webappdb