apiVersion: apps/v1
kind: Deployment # it will invoker the deployment api
metadata:
  name: mysql 
spec:
  replicas: 1 #i want to create three pod
  selector: #all this three pod will have a lablem of app:myapp3
    matchLabels:
      app: mysql
  strategy:
    type: Recreate 
  template:
    metadata:
      labels:
        app: mysql 
    spec:
      containers:
        - name: mysql 
          image: mysql:5.6
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: dbpassword11
          ports:
            - containerPort: 3306
              name: mysql 
          volumeMounts:
            - name: mysql-presistent-volume
              mountPath: /var/lib/mysql
            - name: usermanagement-dbcreation-script
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: mysql-presistent-volume
          persistentVolumeClaim:
              claimName: azure-managed-disk-pvc
        - name: usermanagement-dbcreation-script
          configMap:
              name: usermanagement-dbcreation-script
   