apiVersion: v1
kind: Service
metadata:
  name: myapp-pod-loadbalancer-service
spec:
  type: LoadBalancer #cluserIp #NodePort
  selector: #matchexpression
    app: myapp 
  ports:
    - name: http
      port: 80 #service Port
      targetPort: 80 #container port