apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: managed-premium-retain-sc
provisioner: kubernetes.io/azure-disk
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer #immediate when i launch a pod in the pod defination i have put storage information. till the pod is not up and running this storage will not be used
allowVolumeExpansion: true
parameters:
  storageaccounttype: Premium_LRS
  kind: managed
